# vim:sw=2:ts=2
# static linters which can be run in a single repo (do not need phoenix-rtos-project)
name: lint

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  clang-format:
    if: github.event_name == 'push'
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 3  # current PR merge commit + 1 back

      - uses: reviewdog/action-setup@v1
        if: false

      # upstream reviewdog doesn't work for now, sideload our static binary
      - name: Install reviewdog
        run: |
          wget http://misc.nalajcie.org/reviewdog -O /tmp/reviewdog 2>/dev/null
          chmod +x /tmp/reviewdog

      - name: clang-format
        if: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff -U0 HEAD^ | clang-format-diff-10 -p1 | /tmp/reviewdog -f=diff -f.diff.strip=0 -name=clang-format -reporter=github-check

  # reviewdog: use clang-format for PR review
  clang-format-pr:
    if: github.event_name == 'pull_request'
    name: clang-format-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # current PR merge commit + 1 back

      - uses: reviewdog/action-setup@v1
        if: false

      # upstream reviewdog doesn't work for now, sideload our static binary
      - name: Install reviewdog
        run: |
          wget http://misc.nalajcie.org/reviewdog -O /tmp/reviewdog 2>/dev/null
          chmod +x /tmp/reviewdog

      - name: clang-format
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff -U0 HEAD^ | clang-format-diff-10 -p1 | /tmp/reviewdog -f=diff -f.diff.strip=0 -name=clang-format-pr -reporter=github-pr-review -fail-on-error


  # reviewdog: codespell for PRs only
  codespell-pr:
    if: github.event_name == 'pull_request'
    name: codespell-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # current PR merge commit + 1 back

      - name: codespell
        uses: plettich/action-codespell@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review


  # reviewdog: shellcheck
  shellcheck-pr:
    if: github.event_name == 'pull_request'
    name: shellcheck-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
